CREATE TABLE IF NOT EXISTS market_rss_bullish_articles (
  id BIGSERIAL PRIMARY KEY,
  source TEXT NOT NULL,
  external_id TEXT NOT NULL,
  source_article_id BIGINT NOT NULL REFERENCES market_rss_articles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  translated_title TEXT,
  summary TEXT NOT NULL DEFAULT '',
  translated_summary TEXT,
  content TEXT NOT NULL DEFAULT '',
  link TEXT NOT NULL DEFAULT '',
  published_at TIMESTAMPTZ,
  ticker TEXT,
  category TEXT NOT NULL,
  direction TEXT NOT NULL,
  matched_terms TEXT[] NOT NULL DEFAULT '{}',
  priority INTEGER NOT NULL DEFAULT 0,
  financing_amount_usd DOUBLE PRECISION,
  dilution_risk TEXT,
  translation_status TEXT NOT NULL DEFAULT 'PENDING',
  translation_fallback BOOLEAN NOT NULL DEFAULT FALSE,
  translation_error TEXT,
  analyzed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT market_rss_bullish_source_external_unique UNIQUE (source, external_id),
  CONSTRAINT market_rss_bullish_source_article_unique UNIQUE (source_article_id)
);
CREATE INDEX IF NOT EXISTS market_rss_bullish_published_idx ON market_rss_bullish_articles (published_at DESC, priority DESC);
