ALTER TABLE us_turnover_ratio_snapshots
  ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS open DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS high DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS low DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS change_rate DOUBLE PRECISION;
