"use client";
import { useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import styles from "@/app/admin/observability/observability.module.css";
type Row={calls:number;success:number;failures?:number;avg_duration_ms:number;max_duration_ms?:number;day?:string;hour?:string;feature?:string;market?:string};
type Data={summary:Row;daily:Row[];hourly:Row[];features:Row[]};
type Rate={summary:{events:number;incidents:number;recovered:number;max_observed_tps:number;avg_backoff_ms:number};byType:Array<{limit_type:string;limit_scope:string;events:number}>;byEndpoint:Array<{endpoint:string;tr_id:string;events:number}>;events:Array<{id:number;endpoint:string;kis_msg_cd?:string;limit_type:string;occurred_at:string}>};
const n=(v:unknown)=>Number(v??0).toLocaleString("ko-KR");
export function AdminKisCalls(){const[data,setData]=useState<Data|null>(null);const[rate,setRate]=useState<Rate|null>(null);const[days,setDays]=useState(7);const[loading,setLoading]=useState(true);const[error,setError]=useState("");async function load(){setLoading(true);try{const[a,b]=await Promise.all([fetch(`/api/debug/kis-calls?days=${days}&limit=1`,{cache:"no-store"}),fetch(`/api/admin/kis-rate-limits?days=${days}&limit=20`,{cache:"no-store"})]);if(!a.ok)throw Error();setData(await a.json());if(b.ok)setRate(await b.json());}catch{setError("KIS 호출량 집계를 불러오지 못했습니다.");}finally{setLoading(false);}}useEffect(()=>{void load()},[days]);const s=data?.summary;const r=rate?.summary;return <section className={styles.container}><header className={styles.toolbar}><div><strong>실제 호출 집계</strong><p>최근 {days}일</p></div><div className={styles.toolbarActions}><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>최근 1일</option><option value={7}>최근 7일</option><option value={30}>최근 30일</option></select><button className={styles.refreshButton} onClick={()=>void load()} disabled={loading}><RefreshCw size={15}/> 새로고침</button></div></header>{error&&<p className={styles.error}>{error}</p>}{loading&&!data?<p className={styles.empty}>집계 중입니다.</p>:s&&<><div className={styles.summary}><div><dt>총 호출</dt><dd>{n(s.calls)}회</dd></div><div><dt>성공</dt><dd>{n(s.success)}회</dd></div><div><dt>실패</dt><dd>{n(s.failures)}회</dd></div><div><dt>평균 지연</dt><dd>{n(Math.round(s.avg_duration_ms))}ms</dd></div><div><dt>최대 지연</dt><dd>{n(s.max_duration_ms)}ms</dd></div></div><div className={styles.grid}>{data.features.map(x=><article className={styles.card} key={`${x.feature}:${x.market}`}><h2>{x.feature} · {x.market}</h2><p>{n(x.calls)}회 · 평균 {n(Math.round(x.avg_duration_ms))}ms</p></article>)}</div></>}{r&&<><header className={styles.toolbar}><div><strong>RATE LIMIT 이벤트</strong><p>전용 감사 로그 · 운영 보호 한도 10 TPS</p></div></header><div className={styles.summary}><div><dt>이벤트</dt><dd>{n(r.events)}건</dd></div><div><dt>Incident</dt><dd>{n(r.incidents)}건</dd></div><div><dt>복구 완료</dt><dd>{n(r.recovered)}건</dd></div><div><dt>최대 관측 TPS</dt><dd>{n(r.max_observed_tps)}</dd></div><div><dt>평균 Backoff</dt><dd>{n(Math.round(r.avg_backoff_ms))}ms</dd></div></div><div className={styles.grid}><article className={styles.card}><h2>유형·범위</h2>{rate!.byType.map(x=><p key={`${x.limit_type}:${x.limit_scope}`}>{x.limit_type} · {x.limit_scope} · <strong>{n(x.events)}건</strong></p>)}</article><article className={styles.card}><h2>엔드포인트</h2>{rate!.byEndpoint.map(x=><p key={`${x.endpoint}:${x.tr_id}`}>{x.endpoint} · {x.tr_id} · <strong>{n(x.events)}건</strong></p>)}</article><article className={styles.card}><h2>최근 이벤트</h2>{rate!.events.map(x=><p key={x.id}>{new Date(x.occurred_at).toLocaleString("ko-KR")} · {x.limit_type} · {x.kis_msg_cd??"-"}</p>)}</article></div></>}</section>}
