"use client";

import { useEffect, useState } from "react";
import type { FeatureModuleKey } from "@/lib/feature-modules";
import styles from "./feature-module-operations.module.css";

export function FeatureModuleOperations({ moduleKey }: { moduleKey: FeatureModuleKey }) {
  const [settings, setSettings] = useState<any>({ enabled: true, startTime: "17:00", endTime: "02:00", cooldownSeconds: 60, intervalSeconds: 600, activeDays: [1, 2, 3, 4, 5], featureSettings: { vwapPolicy: { minAbovePercent: 0, minVolume: 0, minTradeValue: 0, minPointCount: 1, minTurnoverRatio: 0, requireComplete: true } } });
  const [message, setMessage] = useState("");
  useEffect(() => { void fetch(`/api/admin/feature-modules/${moduleKey}`, { cache: "no-store" }).then((response) => response.json()).then(setSettings); }, [moduleKey]);
  async function save() { const response = await fetch(`/api/admin/feature-modules/${moduleKey}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(settings) }); setMessage(response.ok ? "공통 운영 설정이 저장되었습니다." : "저장 실패"); }
  const weekdays = ["일", "월", "화", "수", "목", "금", "토"];
  const policy = settings.featureSettings?.vwapPolicy || {};
  const updatePolicy = (key: string, value: number | boolean) => setSettings({ ...settings, featureSettings: { ...settings.featureSettings, vwapPolicy: { ...policy, [key]: value } } });
  return <section className={styles.panel}><div><h2>공통 운영 설정</h2><p>ON/OFF, KST 스케줄, 활성화 요일, 알림 쿨다운은 기능별로 관리합니다.</p></div><label className={styles.toggle}><input type="checkbox" checked={settings.enabled} onChange={(event) => setSettings({ ...settings, enabled: event.target.checked })} /><span>기능 활성화</span></label><div className={styles.fields}><label>시작 시각<input type="time" value={settings.startTime} onChange={(event) => setSettings({ ...settings, startTime: event.target.value })} /></label><label>종료 시각<input type="time" value={settings.endTime} onChange={(event) => setSettings({ ...settings, endTime: event.target.value })} /></label><label>알림 쿨다운(초)<input type="number" min="0" value={settings.cooldownSeconds} onChange={(event) => setSettings({ ...settings, cooldownSeconds: Number(event.target.value) })} /></label>{moduleKey === "us-daily-indicators" && <label>실행 간격(초)<input type="number" min="60" value={settings.intervalSeconds ?? 600} onChange={(event) => setSettings({ ...settings, intervalSeconds: Number(event.target.value) })} /></label>}</div><div className={styles.fields}>{weekdays.map((label, day) => <label key={day}><input type="checkbox" checked={settings.activeDays.includes(day)} onChange={(event) => setSettings({ ...settings, activeDays: event.target.checked ? [...settings.activeDays, day].sort() : settings.activeDays.filter((value: number) => value !== day) })} /> {label}</label>)}</div>{moduleKey === "us-vwap" && <><h3>VWAP 필터</h3><div className={styles.fields}><label>최소 상회율(%)<input type="number" min="0" step="0.1" value={policy.minAbovePercent ?? 0} onChange={(event) => updatePolicy("minAbovePercent", Number(event.target.value))} /></label><label>시총 대비 거래대금 최소(%)<input type="number" min="0" step="0.1" value={policy.minTurnoverRatio ?? 0} onChange={(event) => updatePolicy("minTurnoverRatio", Number(event.target.value))} /></label><label>최소 거래량<input type="number" min="0" value={policy.minVolume ?? 0} onChange={(event) => updatePolicy("minVolume", Number(event.target.value))} /></label><label>최소 거래대금(USD)<input type="number" min="0" value={policy.minTradeValue ?? 0} onChange={(event) => updatePolicy("minTradeValue", Number(event.target.value))} /></label><label>최소 데이터 포인트<input type="number" min="1" value={policy.minPointCount ?? 1} onChange={(event) => updatePolicy("minPointCount", Number(event.target.value))} /></label></div><label className={styles.toggle}><input type="checkbox" checked={policy.requireComplete !== false} onChange={(event) => updatePolicy("requireComplete", event.target.checked)} /><span>전체 세션 데이터 완료만 허용</span></label></> }<div className={styles.footer}><span>{message}</span><button onClick={() => void save()}>설정 저장</button></div></section>;
}
