"use client";
import { useEffect, useMemo, useState } from "react";
type Item = { id:number; market:string; code:string|null; companyName:string; eventType:string; eventDate:string; eventEndDate:string|null; title:string; description:string; source:string; sourceUrl:string|null };
const types = [["ALL","전체 일정"],["IPO","신규 상장"],["EARNINGS","실적 발표"],["EX_DIVIDEND","배당락"],["DIVIDEND_PAYMENT","배당 지급"],["SHAREHOLDER_MEETING","주주총회"],["LOCKUP_EXPIRY","보호예수 해제"]];
const labels: Record<string,string> = Object.fromEntries(types);
export function InvestmentCalendarPage() {
  const today = new Date().toISOString().slice(0,10); const [from,setFrom]=useState(today); const [to,setTo]=useState(new Date(Date.now()+45*86400000).toISOString().slice(0,10)); const [type,setType]=useState("ALL"); const [market,setMarket]=useState("ALL"); const [items,setItems]=useState<Item[]>([]); const [status,setStatus]=useState("");
  useEffect(()=>{setStatus("불러오는 중…"); const q=new URLSearchParams({from,to}); if(type!=="ALL")q.set("type",type); if(market!=="ALL")q.set("market",market); fetch(`/api/investment-calendar?${q}`,{cache:"no-store"}).then(r=>r.json()).then(b=>setItems(Array.isArray(b.items)?b.items:[])).catch(()=>setStatus("일정 조회에 실패했습니다.")).finally(()=>setStatus(""));},[from,to,type,market]);
  const grouped=useMemo(()=>items.reduce<Record<string,Item[]>>((a,x)=>{(a[x.eventDate]??=[]).push(x); return a;},{}),[items]);
  const todayCount=items.filter(x=>x.eventDate===today).length, nextSeven=items.filter(x=>x.eventDate>=today&&x.eventDate<=new Date(Date.now()+7*86400000).toISOString().slice(0,10)).length;
  async function copyJson(){await navigator.clipboard?.writeText(JSON.stringify({from,to,type,market,count:items.length,items},null,2));setStatus("필터 결과 JSON을 복사했습니다.");window.setTimeout(()=>setStatus(""),1800);}
  return <section className="inquiryBoard investmentCalendarBoard"><div className="inquiryBoardHead"><div><div className="kicker">INVESTMENT CALENDAR</div><h2>투자 일정</h2><p>상장·실적·배당 등 투자 판단에 필요한 일정을 한눈에 확인합니다.</p></div><div className="calendarControls"><label>시작일<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>종료일<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div></div><div className="calendarStats"><div><small>오늘</small><strong>{todayCount}</strong></div><div><small>7일 내</small><strong>{nextSeven}</strong></div><div><small>신규 상장</small><strong>{items.filter(x=>x.eventType==="IPO").length}</strong></div><div><small>실적·배당</small><strong>{items.filter(x=>x.eventType==="EARNINGS"||x.eventType.includes("DIVIDEND")).length}</strong></div></div><div className="calendarFilters"><div className="calendarChips">{types.map(([v,l])=><button key={v} type="button" className={type===v?"calendarChip active":"calendarChip"} onClick={()=>setType(v)}>{l}</button>)}</div><div className="calendarFilterRight"><select value={market} onChange={e=>setMarket(e.target.value)} aria-label="시장"><option value="ALL">전체 시장</option><option value="KR">국내</option><option value="US">해외</option></select><button type="button" className="calendarExport" onClick={()=>void copyJson()}>JSON 복사</button></div></div>{status&&<p role="status">{status}</p>}{!status&&!items.length&&<div className="calendarEmpty">선택한 기간에 저장된 일정이 없습니다.</div>}<div className="calendarTimeline">{Object.entries(grouped).map(([date,dayItems])=><div className="calendarDay" key={date}><time>{date}</time><div>{dayItems.map(item=><article className="calendarEvent" key={item.id}><span className={`calendarBadge calendar-${item.eventType.toLowerCase()}`}>{labels[item.eventType]??item.eventType}</span><div><strong>{item.title}</strong><p>{item.companyName}{item.code?` · ${item.code}`:""} · {item.market}</p>{item.description&&<small>{item.description}</small>}</div><em>{item.sourceUrl?<a href={item.sourceUrl} target="_blank" rel="noreferrer">원문 ↗</a>:item.source}</em></article>)}</div></div>)}</div></section>;
}
