"use client";
import { useCallback, useEffect, useState } from "react";
import { ChartModal } from "@/components/chart-modal";
import styles from "./us-top-rising-chart-page.module.css";
type Item={market:"KOSPI"|"KOSDAQ";code:string;name?:string;rank?:number;rate?:number};
export function KrTopRisingChartPage(){
 const [items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState<number|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[status,setStatus]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch("/api/stock/kr/top-rising-chart",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error??`HTTP ${r.status}`);setItems(b.items??[]);setStatus(b.message??null);}catch(e){setError(e instanceof Error?e.message:"조회에 실패했습니다.");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]); const current=selected==null?null:items[selected]??null;
 return <main className={styles.page}><section className={styles.hero}><div className={styles.eyebrow}>KR MARKET · MEMORY UNIVERSE</div><div className={styles.heroRow}><div><h1>국내 상승률 <span>TOP 100</span></h1><p>장중 메모리에 보관된 KOSPI·KOSDAQ 상승률 후보를 차트로 확인합니다.</p></div><button className={styles.refresh} onClick={()=>void load()} disabled={loading}>{loading?"조회 중…":"↻ 메모리 갱신"}</button></div><div className={styles.stats}><span><b>{items.length}</b> 전체 종목</span><span>데이터 소스 <b>MEMORY</b></span></div></section><section className={styles.panel}><div className={styles.toolbar}><strong>상승률 랭킹</strong></div>{error&&<div className={styles.stateError} role="alert">{error}<button onClick={()=>void load()}>다시 시도</button></div>}{loading&&!items.length&&<div className={styles.state}>메모리 스냅샷을 불러오는 중입니다.</div>}{!loading&&!error&&status&&<div className={styles.state} role="status">{status}</div>}<div className={styles.grid}>{items.map((item,i)=><article className={styles.card} key={`${item.market}:${item.code}`}><div className={styles.rank}>#{String(item.rank??i+1).padStart(2,"0")}</div><div className={styles.identity}><strong>{item.name||"회사명 확인 중"}</strong><small>{item.code} · {item.market}</small></div><div className={styles.change}><b>{item.rate==null?"-":`${item.rate>0?"+":""}${item.rate}%`}</b><small>상승률</small></div><button className={styles.chartButton} onClick={()=>setSelected(i)}>차트 보기 <span>→</span></button></article>)}</div></section>{current&&<ChartModal code={current.code} company={current.name||current.code} exchange={current.market} position={{current:selected!+1,total:items.length}} onClose={()=>setSelected(null)} onPrevious={selected!>0?()=>setSelected(selected!-1):undefined} onNext={selected!<items.length-1?()=>setSelected(selected!+1):undefined}/>}</main>;
}
