"use client";
import { useEffect, useState } from "react";
import styles from "./notes-workbench.module.css";
type Note={id:number;title:string;content:string;createdAt:string;updatedAt:string};
function preview(value:string){return value.split("\n").map((line,i)=>{const safe=line.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); const html=safe.replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/`(.+?)`/g,"<code>$1</code>"); return <div key={i} dangerouslySetInnerHTML={{__html:html||" "}}/>;});}
export function NotesWorkbench(){const [notes,setNotes]=useState<Note[]>([]);const [active,setActive]=useState<Note|null>(null);const [title,setTitle]=useState("");const [content,setContent]=useState("");const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
 useEffect(()=>{fetch("/api/notes",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(b=>setNotes(b.notes??[])).catch(()=>setMessage("메모를 사용하려면 로그인해 주세요."));},[]);
 function select(note:Note){setActive(note);setTitle(note.title);setContent(note.content);setMessage("");} function newNote(){setActive(null);setTitle("");setContent("");setMessage("");}
 async function save(){if(!title.trim())return setMessage("제목을 입력하세요.");setSaving(true);const edit=active;const r=await fetch(edit?`/api/notes/${edit.id}`:"/api/notes",{method:edit?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title,content})});const b=await r.json();setSaving(false);if(!r.ok)return setMessage("저장하지 못했습니다.");const note=b.note as Note;setNotes(old=>edit?old.map(n=>n.id===note.id?note:n):[note,...old]);setActive(note);setMessage("저장했습니다.");}
 async function remove(){if(!active||!confirm("이 메모를 삭제할까요?"))return;const r=await fetch(`/api/notes/${active.id}`,{method:"DELETE"});if(r.ok){setNotes(old=>old.filter(n=>n.id!==active.id));newNote();setMessage("삭제했습니다.");}}
 return <section className={styles.layout}><aside className={styles.sidebar}><div className={styles.sideHead}><h2>내 메모 <span>{notes.length}</span></h2><button onClick={newNote}>＋ 새 메모</button></div>{notes.length===0?<p className={styles.empty}>아직 메모가 없습니다.</p>:notes.map(n=><button className={`${styles.noteItem} ${active?.id===n.id?styles.selected:""}`} key={n.id} onClick={()=>select(n)}><strong>{n.title}</strong><small>{new Date(n.updatedAt).toLocaleDateString("ko-KR")}</small></button>)}</aside><div className={styles.editor}><div className={styles.editorTop}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="메모 제목" aria-label="메모 제목"/><div><button className={styles.save} onClick={save} disabled={saving}>{saving?"저장 중…":"저장"}</button>{active&&<button className={styles.delete} onClick={remove}>삭제</button>}</div></div><div className={styles.columns}><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="# 오늘의 메모\n\nMarkdown 형식으로 자유롭게 작성하세요." aria-label="메모 내용"/><article className={styles.preview}><span>미리보기</span>{preview(content)}</article></div>{message&&<p className={styles.message} role="status">{message}</p>}</div></section>}
