"use client";
import { useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import styles from "@/app/admin/observability/observability.module.css";
type Snapshot = { summary: { requests: number; users: number; errors: number }; users: Array<{ userKey: string; count: number; ip: string; country: string | null; region: string | null; city: string | null }>; recent: Array<{ id: number; method: string; path: string; statusCode: number | null; feature?: string; action?: string; resource?: string | null; result?: string | null; userKey: string; ip: string; userAgent: string; country: string | null; region: string | null; city: string | null; createdAt: string }> };
const featureLabels: Record<string, string> = { auth: "인증", screener: "종목 추출", chart: "차트", watchlist: "관심종목", news: "뉴스·공시", community: "커뮤니티", notice: "공지", api: "기타" };
const actionLabels: Record<string, string> = { view: "조회", submit: "실행", copy_json: "JSON 복사", request: "요청" };
export function UserActivityDashboard() {
  const [data, setData] = useState<Snapshot | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState("");
  async function load(userKey = selected) { setLoading(true); setError(""); try { const query = userKey ? `&userKey=${encodeURIComponent(userKey)}` : ""; const response = await fetch(`/api/admin/user-activity?hours=24${query}`, { cache: "no-store" }); if (!response.ok) throw new Error(); setData(await response.json()); } catch { setError("행동 로그를 불러오지 못했습니다."); } finally { setLoading(false); } }
  useEffect(() => { void load(""); }, []);
  if (loading && !data) return <p className={styles.empty}>행동 로그를 불러오는 중입니다.</p>;
  if (error) return <p className={styles.error}>{error}</p>;
  if (!data) return null;
  return <section className={styles.container}><header className={styles.toolbar}><div><strong>{selected ? `사용자 ${selected}` : "최근 24시간 사용자 행동"}</strong><p>사용자가 실행한 기능을 중심으로 확인합니다.</p></div><button className={styles.refreshButton} onClick={() => void load()} disabled={loading}><RefreshCw size={15} /> 새로고침</button></header><div className={styles.grid}><article className={styles.card}><h2>기록된 행동</h2><strong>{data.summary.requests.toLocaleString()}건</strong></article><article className={styles.card}><h2>활동 사용자</h2><strong>{data.summary.users.toLocaleString()}명</strong></article><article className={styles.card}><h2>오류 행동</h2><strong>{data.summary.errors.toLocaleString()}건</strong></article></div><article className={styles.card}><h2>사용자별 활동</h2>{data.users.map((row) => <button type="button" key={row.userKey} className={styles.userRow} onClick={() => { setSelected(row.userKey); void load(row.userKey); }}><strong>{row.userKey}</strong><span>{row.count}회</span><small>{row.ip} · {[row.country, row.region, row.city].filter(Boolean).join(" / ") || "지역 미확인"}</small></button>)}</article><article className={styles.card}><h2>최근 행동{selected ? ` · ${selected}` : ""}</h2><div className={styles.activityList}>{data.recent.slice(0, 100).map((row) => <div key={row.id} className={styles.activityRow}><div className={styles.activityMain}><div><span className={styles.featureBadge}>{featureLabels[row.feature ?? "api"] ?? row.feature}</span><span className={styles.actionBadge}>{actionLabels[row.action ?? "request"] ?? row.action}</span><strong>{row.resource || row.path}</strong></div><small>{row.userKey} · {new Date(row.createdAt).toLocaleString("ko-KR")}</small></div><span className={(row.result === "failed" || (row.statusCode ?? 200) >= 400) ? styles.failure : styles.success}>{(row.result === "failed" || (row.statusCode ?? 200) >= 400) ? "실패" : "성공"}</span></div>)}</div></article></section>;
}
