import { describe, expect, it, vi } from "vitest";
import { IntradayMemoryState } from "./intraday-memory-state";
describe("IntradayMemoryState", () => {
  it("tracks snapshot entries and exits", () => { const state = new IntradayMemoryState(); state.rotateSnapshot([{ market: "NAS", code: "A" }]); expect(state.rotateSnapshot([{ market: "NAS", code: "B" }])).toMatchObject({ entered: ["NAS:B"], exited: ["NAS:A"] }); });
  it("accumulates VWAP only within the same session", () => { const state = new IntradayMemoryState(); state.updateVwap("NAS", "A", "2026-09-12", 10, 100); expect(state.updateVwap("NAS", "A", "2026-09-12", 10, 300).vwap).toBe(20); expect(state.updateVwap("NAS", "A", "2026-09-13", 5, 50).vwap).toBe(10); });
  it("shares in-flight work", async () => { const state = new IntradayMemoryState(); const task = vi.fn(async () => 42); const [a, b] = await Promise.all([state.shared("A", task), state.shared("A", task)]); expect([a, b]).toEqual([42, 42]); expect(task).toHaveBeenCalledTimes(1); });
  it("evicts lowest priority candidates over the configured cap", () => { const state = new IntradayMemoryState(1); state.upsertCandidate({ market: "NAS", code: "A", priority: 1, lastSeenAt: 1, lastCheckedAt: 1, nextCheckAt: 1, consecutiveFailures: 0 }); state.upsertCandidate({ market: "NAS", code: "B", priority: 2, lastSeenAt: 2, lastCheckedAt: 2, nextCheckAt: 2, consecutiveFailures: 0 }); expect(state.getCandidate("NAS", "A")).toBeUndefined(); expect(state.getCandidate("NAS", "B")).toBeDefined(); });
  it("returns due candidates in priority order and schedules high priority faster", () => { const state = new IntradayMemoryState(); state.upsertCandidate({ market: "NAS", code: "A", priority: 130, lastSeenAt: 1, lastCheckedAt: 0, nextCheckAt: 100, consecutiveFailures: 0 }); state.upsertCandidate({ market: "NAS", code: "B", priority: 60, lastSeenAt: 2, lastCheckedAt: 0, nextCheckAt: 100, consecutiveFailures: 0 }); expect(state.dueCandidates(100).map((x) => x.code)).toEqual(["A", "B"]); expect(state.scheduleCandidate("NAS", "A", 100)?.nextCheckAt).toBe(10100); });
});
