import { and, desc, eq, or, sql } from "drizzle-orm";
import { getDb } from "@/lib/db";
import { krDailyPriceCandles, krMarketSnapshots } from "@/lib/schema";
import type { OHLCVCandle } from "@/lib/kis-chart";
import { fetchKrDailyPrice } from "@/lib/kis-kr-daily-price";
import { fetchKrPriceDetail } from "@/lib/kis-kr-price-detail";
export async function loadCachedKrDailyCandlesBulk(items:Array<{market:string;code:string}>, limit=100) { const db=getDb(); const result=new Map<string,OHLCVCandle[]>(); if(!items.length)return result; const filters=items.map(i=>and(eq(krDailyPriceCandles.market,i.market),eq(krDailyPriceCandles.code,i.code))); const rows=await db.select().from(krDailyPriceCandles).where(or(...filters)).orderBy(desc(krDailyPriceCandles.candleDate)); for(const row of rows){const key=`${row.market}:${row.code}`;const arr=result.get(key)??[];if(arr.length<limit)arr.push({date:row.candleDate,open:row.open,high:row.high,low:row.low,close:row.close,volume:row.volume});result.set(key,arr);} return result; }
export async function saveKrDailyCandles(market:string,code:string,candles:OHLCVCandle[]){if(!candles.length)return 0; await getDb().insert(krDailyPriceCandles).values(candles.map(c=>({market,code,candleDate:c.date,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume,source:"KIS"}))).onConflictDoUpdate({target:[krDailyPriceCandles.market,krDailyPriceCandles.code,krDailyPriceCandles.candleDate],set:{open:sql`excluded.open`,high:sql`excluded.high`,low:sql`excluded.low`,close:sql`excluded.close`,volume:sql`excluded.volume`,fetchedAt:new Date()}});return candles.length;}
export async function refreshKrDailyCandles(code:string){const response=await fetchKrDailyPrice({code});if(response?.ok&&response.candles.length)await saveKrDailyCandles("KRX",code,response.candles);return response;}
export async function loadKrMarketMetrics(items:Array<{market:string;code:string}>){const rows=items.length?await getDb().select().from(krMarketSnapshots).where(or(...items.map(i=>and(eq(krMarketSnapshots.market,i.market),eq(krMarketSnapshots.code,i.code))))):[];return new Map(rows.map(row=>[`${row.market}:${row.code}`,{marketCap:row.marketCap,turnoverRatio:row.turnoverRatio,price:row.price,volume:row.volume,tradingValue:row.tradingValue}]));}
export async function refreshKrMarketSnapshot(code:string){const response=await fetchKrPriceDetail(code);if(!response?.ok)return response;await getDb().insert(krMarketSnapshots).values({market:"KRX",code,price:response.price,volume:response.volume,tradingValue:response.tradingValue,marketCap:response.marketCap,turnoverRatio:response.turnoverRatio,changeRate:response.changeRate,rawPayload:response.rawText,observedAt:new Date()}).onConflictDoUpdate({target:[krMarketSnapshots.market,krMarketSnapshots.code],set:{price:response.price,volume:response.volume,tradingValue:response.tradingValue,marketCap:response.marketCap,turnoverRatio:response.turnoverRatio,changeRate:response.changeRate,rawPayload:response.rawText,observedAt:new Date()}});return response;}
