import { scanMultiTimeframeBbPullback } from "@/lib/multi-timeframe-bb-pullback";

type Result = Awaited<ReturnType<typeof scanMultiTimeframeBbPullback>>;
const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>\"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" })[c] ?? c);

export function renderMultiTimeframeBbHtml(results: Result[], generatedAt: string) {
  const rows = results.flatMap((result) => result.qualified as any[]);
  const kr = results.find((result) => result.market === "KR");
  const us = results.find((result) => result.market === "US");
  const row = (item: any) => `<tr><td>${escapeHtml(item.market)}</td><td>${escapeHtml(item.code)}</td><td>${escapeHtml(item.name)}</td><td>${escapeHtml(item.daily?.close)}</td><td>${escapeHtml(item.daily?.bbMiddle)}</td><td>${escapeHtml(item.weekly?.close)}</td><td>${escapeHtml(item.weekly?.bbMiddle)}</td><td>${escapeHtml(item.weekly?.bbUpper)}</td><td>${escapeHtml(item.monthly?.close)}</td><td>${escapeHtml(item.monthly?.bbMiddle)}</td><td>${escapeHtml(item.monthly?.bbUpper)}</td></tr>`;
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StockMan 다중 시간봉 BB 결과</title><style>body{font-family:Arial,sans-serif;background:#0b1220;color:#e5e7eb;margin:0;padding:24px}h1{margin:0 0 8px}.meta{color:#94a3b8;margin-bottom:20px}.cards{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:20px}.card{background:#111c2f;border:1px solid #26364f;border-radius:10px;padding:14px 18px;min-width:130px}.card b{font-size:22px;color:#86efac}table{border-collapse:collapse;width:100%;font-size:13px;background:#111827}th,td{border:1px solid #26364f;padding:8px 7px;text-align:right;white-space:nowrap}th{background:#1e293b;color:#cbd5e1;position:sticky;top:0}td:nth-child(1),td:nth-child(2),td:nth-child(3){text-align:left}tr:nth-child(even){background:#0f172a}</style></head><body><h1>다중 시간봉 볼린저밴드 조건 결과</h1><div class="meta">생성 시각: ${escapeHtml(generatedAt)} (KST) · 조건: 주봉·월봉 종가가 중단선~상단선, 일봉 종가가 중단선 이하</div><div class="cards"><div class="card">국내<br><b>${kr?.qualifiedCount ?? 0}</b>개</div><div class="card">해외<br><b>${us?.qualifiedCount ?? 0}</b>개</div><div class="card">전체<br><b>${rows.length}</b>개</div></div><table><thead><tr><th>시장</th><th>티커</th><th>종목명</th><th>일봉 종가</th><th>일봉 중단</th><th>주봉 종가</th><th>주봉 중단</th><th>주봉 상단</th><th>월봉 종가</th><th>월봉 중단</th><th>월봉 상단</th></tr></thead><tbody>${rows.map(row).join("")}</tbody></table></body></html>`;
}
