import { fetchUsMinuteTurnover } from "@/lib/kis-us-minute-turnover";
import { loadUsTopRisingScopes } from "@/lib/us-top-rising-universe";
import { loadFeatureModuleSettings } from "@/lib/feature-module-settings";
import { writeKisCache } from "@/lib/kis-cache";

export type UsMinuteObvAdlPolicy = { topN: number; obvSignalPeriod: number; adlSignalPeriod: number; requireRisingSignals: boolean; minChangeRate: number };
export type UsMinuteObvAdlResult = { market: string; code: string; name: string; rank: number; changeRate: number | null; pointCount: number; obv: number | null; obvSignal: number | null; adl: number | null; adlSignal: number | null; obvAboveSignal: boolean; adlAboveSignal: boolean; signalsRising: boolean; qualifies: boolean; status: "QUALIFIED" | "NOT_QUALIFIED" | "FAILED"; error?: string };
function ema(values: number[], period: number) { const alpha = 2 / (period + 1); return values.reduce<number[]>((out, value, i) => { out.push(i === 0 ? value : value * alpha + out[i - 1] * (1 - alpha)); return out; }, []); }
export function calculateMinuteObvAdl(points: Array<{ time: string; price: number; volume: number; high?: number; low?: number }>, policy: UsMinuteObvAdlPolicy) {
  const rows = points.filter((p) => Number.isFinite(p.price) && p.price > 0 && Number.isFinite(p.volume) && p.volume >= 0).sort((a, b) => a.time.localeCompare(b.time));
  if (rows.length < Math.max(policy.obvSignalPeriod, policy.adlSignalPeriod) + 1) return { ready: false, pointCount: rows.length, obv: null, obvSignal: null, adl: null, adlSignal: null, obvAboveSignal: false, adlAboveSignal: false, signalsRising: false };
  let obvValue = 0; const obv = rows.map((row, i) => { if (i > 0) obvValue += row.price > rows[i - 1].price ? row.volume : row.price < rows[i - 1].price ? -row.volume : 0; return obvValue; });
  let adlValue = 0; const adl = rows.map((row) => { const high = row.high ?? row.price; const low = row.low ?? row.price; const range = high - low; const multiplier = range > 0 ? ((row.price - low) - (high - row.price)) / range : 0; adlValue += multiplier * row.volume; return adlValue; });
  const os = ema(obv, policy.obvSignalPeriod), as = ema(adl, policy.adlSignalPeriod); const obvSignal = os.at(-1)!, adlSignal = as.at(-1)!;
  return { ready: true, pointCount: rows.length, obv: obv.at(-1)!, obvSignal, adl: adl.at(-1)!, adlSignal, obvAboveSignal: obv.at(-1)! > obvSignal, adlAboveSignal: adl.at(-1)! > adlSignal, signalsRising: os.at(-1)! > (os.at(-2) ?? os.at(-1)!) && as.at(-1)! > (as.at(-2) ?? as.at(-1)!) };
}
export async function scanUsMinuteObvAdl(options: { policy?: Partial<UsMinuteObvAdlPolicy>; concurrency?: number } = {}) {
  const settings = await loadFeatureModuleSettings("us-minute-obv-adl"); const configured = settings.featureSettings?.minuteObvAdlPolicy as Partial<UsMinuteObvAdlPolicy> | undefined;
  const policy: UsMinuteObvAdlPolicy = { topN: Math.max(1, Math.min(100, Math.floor(Number(options.policy?.topN ?? configured?.topN ?? 100)))), obvSignalPeriod: Math.max(2, Math.floor(Number(options.policy?.obvSignalPeriod ?? configured?.obvSignalPeriod ?? 9))), adlSignalPeriod: Math.max(2, Math.floor(Number(options.policy?.adlSignalPeriod ?? configured?.adlSignalPeriod ?? 9))), requireRisingSignals: options.policy?.requireRisingSignals ?? configured?.requireRisingSignals ?? true, minChangeRate: Number(options.policy?.minChangeRate ?? configured?.minChangeRate ?? 0) };
  const universe = await loadUsTopRisingScopes(); const scopes = universe.scopes.filter((s) => (s.rank ?? 999) <= policy.topN && (s.changeRate ?? 0) >= policy.minChangeRate); const results: UsMinuteObvAdlResult[] = []; let cursor = 0; const concurrency = Math.max(1, Math.min(options.concurrency ?? 4, 8));
  async function worker() { while (true) { const scope = scopes[cursor++]; if (!scope) return; try { const response = await fetchUsMinuteTurnover({ code: scope.code, market: scope.market }); const points = (response?.points ?? []).map((p) => ({ time: p.time, price: p.price, volume: p.volume ?? 0, high: p.high, low: p.low })); const c = calculateMinuteObvAdl(points, policy); const qualifies = c.ready && c.obvAboveSignal && c.adlAboveSignal && (!policy.requireRisingSignals || c.signalsRising); results.push({ market: scope.market, code: scope.code, name: scope.name ?? "", rank: scope.rank ?? 0, changeRate: scope.changeRate ?? null, pointCount: c.pointCount, obv: c.obv, obvSignal: c.obvSignal, adl: c.adl, adlSignal: c.adlSignal, obvAboveSignal: c.obvAboveSignal, adlAboveSignal: c.adlAboveSignal, signalsRising: c.signalsRising, qualifies, status: !c.ready ? "FAILED" : qualifies ? "QUALIFIED" : "NOT_QUALIFIED", error: !c.ready ? `insufficient valid 1-minute candles (${c.pointCount})` : undefined }); } catch (error) { results.push({ market: scope.market, code: scope.code, name: scope.name ?? "", rank: scope.rank ?? 0, changeRate: scope.changeRate ?? null, pointCount: 0, obv: null, obvSignal: null, adl: null, adlSignal: null, obvAboveSignal: false, adlAboveSignal: false, signalsRising: false, qualifies: false, status: "FAILED", error: error instanceof Error ? error.message : String(error) }); } } }
  await Promise.all(Array.from({ length: Math.min(concurrency, Math.max(1, scopes.length)) }, worker)); results.sort((a, b) => Number(b.qualifies) - Number(a.qualifies) || a.market.localeCompare(b.market) || a.rank - b.rank);
  const qualified = results.filter((r) => r.qualifies); const payload = { scope: "US", timeframe: "1m", updatedAt: new Date().toISOString(), policy, universe: universe.universe, instrumentCount: scopes.length, successCount: results.filter((r) => r.status !== "FAILED").length, failureCount: results.filter((r) => r.status === "FAILED").length, qualifiedCount: qualified.length, qualified, results };
  await writeKisCache("minute-obv-adl:US:1m", payload); return { ok: universe.universe.ok, ...payload };
}
