import Link from "next/link";
import { PageNavigation } from "@/components/page-navigation";
import { MultiTimeframeReboundCopy } from "@/components/multi-timeframe-rebound-copy";
import { MultiTimeframeApiRunner } from "@/components/multi-timeframe-api-runner";
import { scanMultiTimeframeBbRebound } from "@/lib/multi-timeframe-bb-rebound";
import { recommendMultiTimeframe } from "@/lib/multi-timeframe-recommendations";
import { scanMultiTimeframeBbPullback } from "@/lib/multi-timeframe-bb-pullback";
import styles from "../page.module.css";
export const dynamic = "force-dynamic";
export default async function Page({ searchParams }: { searchParams: Promise<{ market?: string; limit?: string; view?: string }> }) {
  const p = await searchParams; const market = p.market?.toUpperCase() === "KR" ? "KR" : "US"; const limit = Math.max(1, Math.min(100, Number(p.limit ?? 30) || 30)); const view = (["rebound", "recommendations", "pullback", "all-middle-above"].includes(p.view ?? "") ? p.view : "rebound")!;
  const empty: any = { instrumentCount: 0, qualifiedCount: 0, results: [], qualified: [] }; let data: any = empty;
  try { data = view === "rebound" ? await scanMultiTimeframeBbRebound(market, limit) : view === "recommendations" ? await recommendMultiTimeframe(market, "all", limit) : await scanMultiTimeframeBbPullback(market, view === "pullback" ? "pullback" : "all-middle-above"); } catch (e) { data = { ...empty, error: e instanceof Error ? e.message : String(e) }; }
  const items = data.results ?? data.qualified ?? []; const copy = items.map((x: any) => `${x.market} ${x.code} | ${x.name}`).join("\n"); const title = view === "rebound" ? "BB 반등 준비 종목" : view === "recommendations" ? "통합 추천 종목" : view === "pullback" ? "BB 풀백 종목" : "일·주·월봉 중단선 이상 종목";
  return <><PageNavigation current="multi-timeframe-rebound" /><main className={styles.page}><section className={styles.hero}><div className={styles.kicker}>MULTI-TIMEFRAME ANALYSIS</div><h1 className={styles.title}>{title}</h1><p>국내·해외와 탐지 유형을 선택하면 해당 API만 실행합니다.</p></section><div style={{display:"flex",gap:12,justifyContent:"center",flexWrap:"wrap",marginBottom:24}}>{["rebound","recommendations","pullback","all-middle-above"].map(v=><Link key={v} href={`/scanners/multi-timeframe-rebound?market=${market}&view=${v}`}>{v === "rebound" ? "반등" : v === "recommendations" ? "통합 추천" : v === "pullback" ? "BB 풀백" : "중단선 이상"}</Link>)}<Link href={`/scanners/multi-timeframe-rebound?market=KR&view=${view}`}>국내</Link><Link href={`/scanners/multi-timeframe-rebound?market=US&view=${view}`}>해외</Link><MultiTimeframeApiRunner /><MultiTimeframeReboundCopy text={copy} /></div><section style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12,marginBottom:24}}><div>대상 종목<br/><strong>{Number(data.instrumentCount ?? 0).toLocaleString()}</strong></div><div>조건 충족<br/><strong>{Number(data.qualifiedCount ?? 0).toLocaleString()}</strong></div></section><section>{items.map((x: any)=><article key={`${x.market}:${x.code}`} style={{border:"1px solid var(--border-color,#334155)",borderRadius:12,padding:16,marginBottom:12}}><strong>{x.market} {x.code} | {x.name}</strong><div>종가 {x.latest?.close ?? x.daily?.close ?? "-"} · 기준일 {x.latest?.date ?? x.daily?.date ?? "-"}</div><div>일봉·주봉·월봉 조건 충족</div></article>)}</section>{!items.length && <p style={{textAlign:"center",opacity:.75}}>{data.error ?? "조건을 충족하는 종목이 없습니다."}</p>}</main></>;
}

